[package]
name = "ic-rmcp"
version = "0.1.0"
edition = "2021"
description = "Rust SDK for building Model Context Protocol servers on Internet Computer canisters"
license = "MIT"
authors = ["Kyle <lhkhiem@outlook.com>", "Long Tran <tranbaolong14@gmail.com>"]

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
ic-http-certification = "3.0.3"
rmcp = "0.2.1"
ic-cdk = { version = "0.18", features = ["transform-closure"] }
candid = "0.10"
jsonwebtoken = { git = "https://github.com/ByteSmithLabs/jsonwebtoken.git", tag = "v9.3.1-port-wasm-ic" }
url = "2.4.0"

[dev-dependencies]
flate2 = "1.0"
futures = "0.3"
pocket-ic = "16.0.0"
schemars = { version = "0.8" }

